name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt
      
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Deploy code to EC2 instance
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} 'mkdir -p ~/myapp'
          scp -r . ubuntu@${{ secrets.EC2_HOST }}:~/myapp/
          ssh ubuntu@${{ secrets.EC2_HOST }} 'cd ~/myapp && nohup python3 server.py > server.log &'
