name: Deploy to EC2
 
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Add EC2 instance to known hosts
        run: |
          echo "${{ secrets.EC2_HOST }} $(ssh-keyscan -t rsa ${{ secrets.EC2_HOST }})" >> ~/.ssh/known_hosts
          
      - name: Check if process is running on port 4455
        run: |
          PID=$(ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'sudo lsof -t -i :4455 || echo "None"')
          if [[ $PID != "None" ]]; then
            echo "Process is running on port 4455, PID=$PID"
            ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'sudo kill -9 $PID'
            echo "Process killed"
          else
            echo "No process is listening on port 4455"
          fi
      
      - name: Deploy code to EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'sudo apt-get update'
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'sudo apt-get install -y python3-pip'
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'rm -rf cloud-computing-ex1'
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'git clone https://github.com/DorSkoler/cloud-computing-ex1.git'
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'cd ~/cloud-computing-ex1 && git pull'
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'sudo pip3 install -r ~/cloud-computing-ex1/requirements.txt'
          ssh -n -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'cd ~/cloud-computing-ex1 && nohup sudo python3 server.py > server.log &'
